### ISSUE TITLE
Fails to install when portaudio isn't installed

### ISSUE THREAD

**Issue by Haroenv** [trishume/LastSecondSlides#1]
I ran `sudo pip install -r requirements.txt` and i got:

```
[truncated]
    #include "portaudio.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-I545kf/PyAudio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-QFw4C4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-I545kf/PyAudio/
```

I think I don't have portaudio installed currently, I'll try if that fixes the issue.

EDIT: after doing `brew install portaudio` there were no issues installing with pip

Installation instructions in the readme would be cool in the future

**Comment by Haroenv** [comment]
but now I'm pretty clueless on how to start the project

```
LastSecondSlides master ➜ python drawing.py 
Traceback (most recent call last):
  File "drawing.py", line 1, in <module>
    import pygame
ImportError: No module named pygame
LastSecondSlides master ✗ ➜ python speech.py
Traceback (most recent call last):
  File "speech.py", line 23, in <module>
    from gcloud.credentials import get_credentials
  File "/Library/Python/2.7/site-packages/gcloud/credentials.py", line 24, in <module>
    from gcloud._helpers import UTC
  File "/Library/Python/2.7/site-packages/gcloud/_helpers.py", line 28, in <module>
    from google.protobuf import timestamp_pb2
ImportError: cannot import name timestamp_pb2
```

EDIT: needed `pygame` (`brew install homebrew/python/pygame`)  as well.

**Comment by trishume** [comment]
😐 we haven't even finished making it, we started this morning...

**Comment by Haroenv** [comment]
Haha, sorry for the rush then. Seems like a great project ❤️
